### ISSUE TITLE
名字重複

### ISSUE THREAD

**Issue by earthoul** [kmaed/biblatex-japanese#1]
はじめまして :-)

試みにTeX Live 2016環境で`test-japanese.tex`をコンパイルしようと、一旦`sandbox.tex`にrenameしてから

```
lualatex
biber
lualatex
lualatex
```

した結果、`biblatex`から「（BiBTeX用の）古いmacroとかもう使うなよ書き換えといたぞ」とさんざんwarningされたあげく、「保毛保毛太郎」のように和文書籍の名字がすべてダブりました（当方の[OneDrive](https://1drv.ms/f/s!ArtT-qmHSt7M-D0Jncm6vNT15agH)にlog、pdfなどファイル一式置きましたのでご参照ください）。

当方、解析が不案内なので、まずは事象報告まで…。

**Comment by kmaed** [comment]
ありがとうございます&ごめんなさい．Biblatex のアップデートでだめになっていることはずっと前に気付いているのですが，手が回っていません．できるだけ早く直します．

**Comment by kmaed** [comment]
ようやく直しました．着手してみたらあっという間だったので，怠慢という他ありませんでした．今年はもっと迅速に動けるようになりたいです．
