### ISSUE TITLE
delimiter formatの変更について

### ISSUE THREAD

**Issue by ShiroTakeda** [kmaed/biblatex-japanese#12]
現在の biblatex-japanese では bibliography での編集者の表示が

> 有村俊秀，片山東，松本茂，eds.

のようになります．これを

> 有村俊秀，片山東，松本茂編

のように変更するのを次にしたいと思っています．

ここで、最後の editor 「松本茂」と「eds.」の間の「，」（comma + space）は `editortypedelim` という delimiter format で指定されています．

これは biblatex.def で 

    \DeclareDelimFormat{editortypedelim}{\addcomma\space}

と定義されています．

日本語文献の場合 comma + space は不要ですので，何も挿入しないという形に修正をしたいのですが，それには

    \DeclareDelimFormat{editortypedelim}{%
      \iffieldequalstr{langid}{japanese}
        {}
        {\addcomma\space}}

を japanese.lbx に追加すればできます．この方法では直接 DeclareDelimFormat で定義しなおすことになります．

ただ、field format などは `replacefieldformat` コマンドで置き換えをしているので，delimiter についても同じような置き換えの処理をしないと問題があるかもという気もします．

`DeclareDelimFormat` で直接修正するという方法で特に問題ないでしょうか？

**Comment by kmaed** [comment]
ちょっと色々忘れてしまっているので，それでよいか検討してみます．

**Comment by ShiroTakeda** [comment]
ありがとうございます。お時間のあるときでかまいませんので。

**Comment by ShiroTakeda** [comment]
上で書いたあと、自分でもLaTeXの勉強をしようと思っていたのですが、結局進まず、あまり理解ができていないのですが、とりあえず上で書いたように「DeclareDelimFormat」を直接書き換えるという形で修正してみてもよろしいでしょうか？

**Comment by kmaed** [comment]
申し訳ありません．さっぱり時間的余裕ができないので困っていました．

落ち着いて，なんで replace とかやっていたんだっけ，と思い出してみたのですが，おそらく biblatex にはサードパーティの biblatex-** というパッケージがたくさんあって，それらに自然に対応しようとすると上書きより置換の方がよいだろうということだったような気がします．また，そうしておくと元のパッケージがバージョンアップで変更されたときにも何もしなくても対応できます．後者は現実にはあまり意味のない想定かもしれませんが．

それで，FieldFormat や NameFormat は内部構造が同じなので，replace 系コマンドの変種が簡単に定義できるようになっているのですが，DelimFormat は見たところそうではないようで，どういう定義をしているのかちゃんと解析してみないと，私にはすぐにはわからなさそうです．暫定的に `\DeclareDelimFormat` で上書きしてもよいですが，将来的には `\replacedelimformat` を用意した方がよいように見えました．

**Comment by ShiroTakeda** [comment]
ありがとうございます。

とりあえず editortypedelim を japanese.lbx の中で \DeclareDelimFormat で上書きしようかと思いましたが、japanese.lbx の他の部分をよく見てみると、同じように biblatex.def で \DeclareDelimFormat によって定義されている finalnamedelim が以下のように \replacecommand で置き換えられていました。

    \replacecommand{\finalnamedelim}{iflangidisjapanese}{\addcomma}%

ということは editortypedelim も \replacecommand で置き換えるという方がよさそうですが、それでいいでしょうか？

**Comment by kmaed** [comment]
そうか……．それならばそれでとりあえずはよさそうです．ありがとうございます．
（`\DeclareDelimFormat` にあるオプションの `context` が指定できるべきだと思うのですが，昔の私がそこまでちゃんと考えずに直接置換を適用していそうです……．）
