### ISSUE TITLE
日本語文献の日本人著者名の区切「，」を変更可能にしたい

### ISSUE THREAD

**Issue by ShiroTakeda** [kmaed/biblatex-japanese#15]
#8 の中でも挙げていますが，日本語文献の日本人著者名の区切「，」を変更できるようにしたいです．

現在、日本語の複数の著者の名前の区切の記号には「，」が用いられています．
- 例: 「夏目漱石，芥川龍之介」，「夏目漱石，芥川龍之介，太宰治」

しかし、雑誌によっては複数の著者の名前の区切には全角中黒「・」を用いることがあります．
- 例：「夏目漱石・芥川龍之介」，「夏目漱石・芥川龍之介・太宰治」

既定値としては元のままにしておくとしますが，この名前間の区切を変更しやすくしたいと思います．

### 方法

1) まず，japanese.lbx で localized strings に `japanese-name-delimiter` という名前の string を追加．既定値はこれまでの `\addcomma` としておく

```
japanese-name-delimiter = {{\addcomma}}{{\addcomma}}
```

この `japanese-name-delimiter` という名前は私が適当につけたものです（他の名前でもかまいません）．

2) 名前の間の区切を設定する `\finalnamdelim` と `\multinamedelim` を修正（`\replacecommand`で置き換え）。

+ 注：`\multinamedelim` は以下の A の部分にはいるもの，`\finalnamdelim` は B の部分にはいるもの．
+ 「夏目漱石 A 芥川龍之介 B 太宰治」、「夏目漱石 B 芥川龍之介」

以上のようにしておくことで、プリアンプルに次のような設定を書きこむことで区切を「・」に変更できます．

```
\DefineBibliographyStrings{japanese}{
japanese-name-delimiter	 = {・},
}
```

カスタマイズするには、プリアンプルで `\finalnamdelim` と `\multinamedelim` を直接書き換えるという方法もありますが、上のようにしておけば、プリアンプルの `\DefineBibliographyStrings` で他の localized string と一緒に変更可能になるのでいいかなと考えています．

以上のようなやり方で修正したいと考えていますが、問題ないでしょうか？

**Comment by kmaed** [comment]
それでよさそうです．ありがとうございます．

**Comment by ShiroTakeda** [comment]
それでは上のような形で修正したいと思います。

**Comment by kmaed** [comment]
ありがとうございました．
